### ISSUE TITLE
光标可以跟随，但是文字上不去

### ISSUE THREAD

**Issue by bb33bb** [AlanSune/JetBrainsRuntime-for-Linux-x64#4]
![image](https://github.com/AlanSune/JetBrainsRuntime-for-Linux-x64/assets/5463104/5468429e-ec34-4d2a-93de-670b357a8175)

![image](https://github.com/AlanSune/JetBrainsRuntime-for-Linux-x64/assets/5463104/16b04fcf-8eeb-4bd5-b794-68c017d1af93)

光标可以跟随，但是文字上不去。如下所示。
谢谢了哈！！
测试的是最新版您刚发布的。

**Comment by AlanSune** [comment]
可以参考 https://developer.aliyun.com/article/979341 先试试方案1和3是否可以解决。

**Comment by AlanSune** [comment]
w

> ![image](https://user-images.githubusercontent.com/5463104/263511847-5468429e-ec34-4d2a-93de-670b357a8175.png)
> 
> ![image](https://user-images.githubusercontent.com/5463104/263511801-16b04fcf-8eeb-4bd5-b794-68c017d1af93.png)
> 
> 光标可以跟随，但是文字上不去。如下所示。 谢谢了哈！！ 测试的是最新版您刚发布的。

我本地系统：ubuntu22.04，idea版本：2023.2.1 (Community Edition)，输入法：fcitx+搜狗，使用正常

**Comment by bb33bb** [comment]
> > ![image](https://user-images.githubusercontent.com/5463104/263511847-5468429e-ec34-4d2a-93de-670b357a8175.png)
> > ![image](https://user-images.githubusercontent.com/5463104/263511801-16b04fcf-8eeb-4bd5-b794-68c017d1af93.png)
> > 光标可以跟随，但是文字上不去。如下所示。 谢谢了哈！！ 测试的是最新版您刚发布的。
> 
> 我本地系统：ubuntu22.04，idea版本：2023.2.1 (Community Edition)，输入法：fcitx+搜狗，使用正常

我去换一个试试，谢谢老哥！！我用的谷歌输入法，我去换个搜狗试试。

**Comment by bb33bb** [comment]
> > > ![image](https://user-images.githubusercontent.com/5463104/263511847-5468429e-ec34-4d2a-93de-670b357a8175.png)
> > > ![image](https://user-images.githubusercontent.com/5463104/263511801-16b04fcf-8eeb-4bd5-b794-68c017d1af93.png)
> > > 光标可以跟随，但是文字上不去。如下所示。 谢谢了哈！！ 测试的是最新版您刚发布的。
> > 
> > 
> > 我本地系统：ubuntu22.04，idea版本：2023.2.1 (Community Edition)，输入法：fcitx+搜狗，使用正常
> 
> 我去换一个试试，谢谢老哥！！我用的谷歌输入法，我去换个搜狗试试。



> > ![image](https://user-images.githubusercontent.com/5463104/263511847-5468429e-ec34-4d2a-93de-670b357a8175.png)
> > ![image](https://user-images.githubusercontent.com/5463104/263511801-16b04fcf-8eeb-4bd5-b794-68c017d1af93.png)
> > 光标可以跟随，但是文字上不去。如下所示。 谢谢了哈！！ 测试的是最新版您刚发布的。
> 
> 我本地系统：ubuntu22.04，idea版本：2023.2.1 (Community Edition)，输入法：fcitx+搜狗，使用正常

经验证，搜狗输入法也失败。可能因为您是community版本，我的版本如下：
CLion 2023.2.1
Build #CL-232.9559.58, built on August 23, 2023
订阅有效期至 2024年5月15日。
For educational use only.
Runtime version: 17.0.7+7-b1000.6 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.5.0-1-manjaro
GC: G1 Young Generation, G1 Old Generation
Memory: 10240M
Cores: 31
Registry:
    run.processes.with.pty=TRUE
    debugger.attach.dialog.enabled=true

Non-Bundled Plugins:
    com.intellij.zh (232.172)

Current Desktop: KDE

**Comment by AlanSune** [comment]
https://developer.aliyun.com/article/979341 中的方案1和3是否验证？

**Comment by bb33bb** [comment]
第三个是ibus，不用验证
第一个验证过了，确实不行。切换环境后，输入法的框从左下角移动到了跟随光标的位置，但是文字在按下空格键后上不去。

**Comment by AlanSune** [comment]
> 

直接安装试试吧，我记得jetbrainToolbox安装有问题。

**Comment by bb33bb** [comment]
> > 
> 
> 直接安装试试吧，我记得jetbrainToolbox安装有问题。

OK，我去试试，有情况我更新过来。

**Comment by bb33bb** [comment]
单独安装后仍旧不行。继续等了。暂时用vscode了

**Comment by sujoshua** [comment]
使用反馈：
使用toolbox安装的最新cilium,
![image](https://github.com/AlanSune/JetBrainsRuntime-for-Linux-x64/assets/54235339/0ef428d4-d742-464a-bda0-036f53d637b6)
使用上周最新的[release](https://github.com/AlanSune/JetBrainsRuntime-for-Linux-x64/releases/tag/jbr-release-21b212.1)的runtime。
在`Linux joshua-manjaro 6.1.44-1-MANJARO #1 SMP PREEMPT_DYNAMIC Wed Aug  9 09:02:26 UTC 2023 x86_64 GNU/Linux` 可以正常跟随输入，并成功输入中文
![image](https://github.com/AlanSune/JetBrainsRuntime-for-Linux-x64/assets/54235339/eeaeaeac-556f-4b3a-b186-02fb973728cc)
![image](https://github.com/AlanSune/JetBrainsRuntime-for-Linux-x64/assets/54235339/99a52779-672f-49a0-9512-1b424170a806)

感谢感谢！

**Comment by AlanSune** [comment]
那我先关闭相关issue啦

**Comment by bb33bb** [comment]
经确定，ibus也修复了该问题。ibus+rime
