### ISSUE TITLE
`GLIBC_2.34' not found 

### ISSUE THREAD

**Issue by aohanhongzhi** [AlanSune/JetBrainsRuntime-for-Linux-x64#5]
![image](https://github.com/AlanSune/JetBrainsRuntime-for-Linux-x64/assets/37319319/3d51221b-8aed-4ec5-ae2e-680aae95da0a)

**Comment by AlanSune** [comment]
> ![image](https://user-images.githubusercontent.com/37319319/263644245-3d51221b-8aed-4ec5-ae2e-680aae95da0a.png)

ubuntu的版本提供下

**Comment by AlanSune** [comment]
已降级打包系统，基于ubuntu20.04打包，如果还有问题请提供系统版本，重新提交issue。
