### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by jococi** [AlanSune/JetBrainsRuntime-for-Linux-x64#6]
![image](https://github.com/AlanSune/JetBrainsRuntime-for-Linux-x64/assets/7496348/b63ba610-bf3b-45e9-8a85-386b87db8877)
![image](https://github.com/AlanSune/JetBrainsRuntime-for-Linux-x64/assets/7496348/9d8a5d3f-e4a5-41be-b857-4dbcf349ca2a)
![image](https://github.com/AlanSune/JetBrainsRuntime-for-Linux-x64/assets/7496348/71006a01-b82e-4031-bede-ded11015b9ab)

**Comment by alan-mikasa** [comment]
> ![image](https://user-images.githubusercontent.com/7496348/268175413-b63ba610-bf3b-45e9-8a85-386b87db8877.png) ![image](https://user-images.githubusercontent.com/7496348/268175439-9d8a5d3f-e4a5-41be-b857-4dbcf349ca2a.png) ![image](https://user-images.githubusercontent.com/7496348/268175574-71006a01-b82e-4031-bede-ded11015b9ab.png)

恢复默认runtime然后重启一下，我刚刚也遇到一样的情况，重启之后就能正常添加了

**Comment by jococi** [comment]
> > ![image](https://user-images.githubusercontent.com/7496348/268175413-b63ba610-bf3b-45e9-8a85-386b87db8877.png) ![image](https://user-images.githubusercontent.com/7496348/268175439-9d8a5d3f-e4a5-41be-b857-4dbcf349ca2a.png) ![image](https://user-images.githubusercontent.com/7496348/268175574-71006a01-b82e-4031-bede-ded11015b9ab.png)
> 
> 恢复默认runtime然后重启一下，我刚刚也遇到一样的情况，重启之后就能正常添加了

我的不行，你用的是什么系统，版本号是多少

**Comment by AlanSune** [comment]
使用打包的最新版本试试，如果还有问题请提供系统、目录相关信息。

**Comment by AlanSune** [comment]
> 使用打包的最新版本试试，如果还有问题请提供系统、目录相关信息。

可以在下载的jdk目录执行下./bin/java -version,看下输出。

**Comment by jococi** [comment]
> > 使用打包的最新版本试试，如果还有问题请提供系统、目录相关信息。
> 
> 可以在下载的jdk目录执行下./bin/java -version,看下输出。
`
./bin/java -version
Error: dl failure on line 580
Error: failed /home/mic/.local/share/JetBrains/JDK/jbr_jcef-17.0.8-linux-x64-b1000.22/lib/server/libjvm.so, because /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/mic/.local/share/JetBrains/JDK/jbr_jcef-17.0.8-linux-x64-b1000.22/lib/server/libjvm.so)
`

应该是依赖问题，我用的是deepin
![image](https://github.com/AlanSune/JetBrainsRuntime-for-Linux-x64/assets/7496348/6341fd5b-f36b-444b-8d12-53f3b2faf508)

**Comment by jococi** [comment]
升级到GLIBC_2.29就好了
