### ISSUE TITLE
空格和鼠标效果不一样，空格，打字会很慢很慢才能上去文字

### ISSUE THREAD

**Issue by bb33bb** [AlanSune/JetBrainsRuntime-for-Linux-x64#8]
空格确认候选文字和鼠标点击确认候选文字效果不一样，空格，打字会很慢很慢才能上去文字
如下视频所示：

https://github.com/AlanSune/JetBrainsRuntime-for-Linux-x64/assets/5463104/d15e2fd1-099a-48e7-b0e1-8b2864782a84

**Comment by AlanSune** [comment]
这个感觉是输入法的问题？除了idea，其他软件有这个问题吗？

**Comment by AlanSune** [comment]
长时间未回复，关闭该issue。
目前官方已在2023.3.1以后版本修复相关bug，请尝试新版本处理。
如果还存在问题，请再提交issue。
